# Generated by Django 5.1.7 on 2025-04-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0005_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='login_time',
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
