# Generated by Django 5.1.7 on 2025-04-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_remove_login_login_time_login_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
