# Generated by Django 5.1.7 on 2025-04-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullname',
            new_name='username',
        ),
    ]
