# Generated by Django 5.1.7 on 2025-04-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0013_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
