# Generated by Django 5.1.7 on 2025-04-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0014_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
