# Generated by Django 5.1.7 on 2025-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0015_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
