# Generated by Django 5.1.7 on 2025-04-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0016_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
