# Generated by Django 5.1.7 on 2025-06-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0018_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_workout_type',
            field=models.CharField(default='push', max_length=20),
        ),
    ]
