# Generated by Django 5.1.7 on 2025-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0019_userprofile_preferred_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_workout_type',
            field=models.CharField(default='cardio', max_length=20),
        ),
    ]
