# Generated by Django 5.1.7 on 2025-06-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0020_alter_userprofile_preferred_workout_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_workout_type',
        ),
    ]
