# Generated by Django 5.1.5 on 2025-06-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0022_exercisehistory_workouthistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workouthistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workouthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExerciseHistory',
        ),
        migrations.DeleteModel(
            name='WorkoutHistory',
        ),
    ]
