# Generated by Django 5.1.5 on 2025-06-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0026_workouthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutHistory',
        ),
    ]
