# Generated by Django 5.1.7 on 2025-06-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0028_dailyworkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyWorkout',
        ),
    ]
