# Generated by Django 5.1.7 on 2025-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0030_generatedworkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedWorkout',
        ),
    ]
