# Generated by Django 5.1.7 on 2025-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0033_foodrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
