# Generated by Django 5.1.7 on 2025-06-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0034_feedback_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_id',
        ),
    ]
