# Generated by Django 5.1.7 on 2025-06-27 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0036_alter_chatmessage_table_alter_feedback_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedworkout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
