# Generated by Django 5.1.7 on 2025-06-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0037_generatedworkout_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedworkout',
            name='created_at',
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
        migrations.AlterModelTable(
            name='foodrecommendation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='generatedworkout',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
