# Generated by Django 5.1.7 on 2025-06-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0038_remove_generatedworkout_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_message',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='foodrecommendation',
            table='food_recommendation',
        ),
        migrations.AlterModelTable(
            name='generatedworkout',
            table='generated_workout',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
