# Generated by Django 5.2.6 on 2026-09-27 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0039_alter_chatmessage_table_alter_feedback_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedworkout',
            name='workout_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='generatedworkout',
            constraint=models.UniqueConstraint(fields=('user', 'day_number'), name='uniq_user_day'),
        ),
        migrations.AlterModelTable(
            name='generatedworkout',
            table=None,
        ),
    ]
