# Generated by Django 5.1.7 on 2025-04-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=20)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
