# Generated by Django 5.1.7 on 2025-04-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
